
server:
  port: 8888

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.2.3.150
          zk-nodes: 10.2.3.150
      bindings:
        helloWorld:
          consumer:
            autoCommitOffset: false
            ackMode: MANUAL_IMMEDIATE
          content-type: application/json